add_newline = true
format = '$directory$git_branch$git_status$character'
palette = 'solarized'

[character]
success_symbol = "[❯](green)"
error_symbol = "[✗](red)"

[directory]
style	= 'bold blue'
truncation_length = 0
truncation_symbol = "…/"
truncate_to_repo = true # обрезать путь, если в git
repo_root_format = '[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) '
repo_root_style = "bold violet"

[git_branch]
format = "[$branch]($style) "
style = "yellow"

[git_status]
format     = '[$all_status$ahead_behind]($style)'
ahead      = "⇡${count}"
diverged   = "⇕⇡${ahead_count}⇣${behind_count}"
behind     = "⇣${count}"

[palettes.solarized]
green = '#859900'
red = '#dc322f'
blue = '#268bd2'
yellow = '#b58900'
violet = '#6c71c4'
magenta = '#d33682'
